#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

export MANWIDTH=999
# use 'bat' as manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
# use 'neovim' as manpager
# export MANPAGER="nvim -c 'set ft=man' -"

export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.npm-packages/bin:$PATH"
export PATH="$HOME/builds/lua-language-server/bin:$PATH"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:/usr/local/go/bin"
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export CLANGD_PATH=$HOME
export BUN_INSTALL="/home/rently/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


