#! /bin/sh

# launch sxhkd for keybindings
sxhkd &

# launch network manager applet
nm-applet --indicator &

# launch flameshot
flameshot &

# launch compton(compositor)
compton &

# launch dunst(notifications)
dunst &

# set wallpaper
feh --bg-fill --randomize ~/Pictures/wallpapers/*

# set left-ptr as mouse cursor
# xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
